# Generated by Django 4.2.7 on 2023-11-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mairie', models.CharField(default='Inconnu', max_length=250)),
                ('ville', models.CharField(max_length=250)),
                ('adresse', models.CharField(max_length=250)),
                ('code_postal', models.FloatField()),
                ('departement', models.CharField(max_length=250)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('label_vvf', models.CharField(max_length=250)),
            ],
        ),
    ]
